// CSS Property Suggestions
export const CSS_PROPERTIES = [
  // Layout
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'z-index',
  'float',
  'clear',
  'overflow',
  'overflow-x',
  'overflow-y',
  'clip',
  'zoom',
  'table-layout',
  'empty-cells',
  'caption-side',
  'vertical-align',
  'text-align',
  'direction',
  'unicode-bidi',

  // Box Model
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-right-radius',
  'border-bottom-left-radius',
  'box-sizing',
  'box-shadow',
  'outline',
  'outline-width',
  'outline-style',
  'outline-color',
  'outline-offset',

  // Typography
  'font',
  'font-family',
  'font-size',
  'font-style',
  'font-variant',
  'font-weight',
  'font-stretch',
  'font-size-adjust',
  'line-height',
  'text-decoration',
  'text-decoration-color',
  'text-decoration-line',
  'text-decoration-style',
  'text-decoration-skip',
  'text-underline-position',
  'text-indent',
  'text-transform',
  'text-shadow',
  'text-align-last',
  'text-justify',
  'word-spacing',
  'letter-spacing',
  'white-space',
  'word-break',
  'word-wrap',
  'overflow-wrap',
  'text-overflow',

  // Visual
  'color',
  'background',
  'background-color',
  'background-image',
  'background-repeat',
  'background-attachment',
  'background-position',
  'background-size',
  'background-clip',
  'background-origin',
  'opacity',
  'filter',
  'backdrop-filter',
  'mix-blend-mode',
  'isolation',
  'transform',
  'transform-origin',
  'transform-style',
  'perspective',
  'perspective-origin',
  'backface-visibility',

  // Animation
  'transition',
  'transition-property',
  'transition-duration',
  'transition-timing-function',
  'transition-delay',
  'animation',
  'animation-name',
  'animation-duration',
  'animation-timing-function',
  'animation-delay',
  'animation-iteration-count',
  'animation-direction',
  'animation-fill-mode',
  'animation-play-state',

  // Flexbox
  'flex',
  'flex-grow',
  'flex-shrink',
  'flex-basis',
  'flex-direction',
  'flex-wrap',
  'flex-flow',
  'justify-content',
  'align-items',
  'align-self',
  'align-content',
  'order',

  // Grid
  'grid',
  'grid-template',
  'grid-template-rows',
  'grid-template-columns',
  'grid-template-areas',
  'grid-row',
  'grid-row-start',
  'grid-row-end',
  'grid-column',
  'grid-column-start',
  'grid-column-end',
  'grid-area',
  'grid-gap',
  'grid-row-gap',
  'grid-column-gap',
  'justify-items',
  'justify-self',
  'align-items',
  'align-self',

  // Other
  'cursor',
  'pointer-events',
  'user-select',
  'resize',
  'content',
  'quotes',
  'counter-reset',
  'counter-increment',
  'list-style',
  'list-style-type',
  'list-style-position',
  'list-style-image',
  'table-border-collapse',
  'table-border-spacing',
  'table-caption-side',
  'table-empty-cells',
  'table-layout',
];

// CSS Value Suggestions for common properties
export const CSS_VALUES: Record<string, string[]> = {
  display: [
    'block',
    'inline',
    'inline-block',
    'flex',
    'grid',
    'none',
    'table',
    'table-cell',
    'table-row',
    'contents',
  ],
  position: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
  float: ['left', 'right', 'none'],
  clear: ['left', 'right', 'both', 'none'],
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'clip'],
  'text-align': ['left', 'right', 'center', 'justify', 'start', 'end'],
  'vertical-align': [
    'baseline',
    'sub',
    'super',
    'top',
    'text-top',
    'middle',
    'bottom',
    'text-bottom',
  ],
  'font-weight': [
    'normal',
    'bold',
    'bolder',
    'lighter',
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
  ],
  'font-style': ['normal', 'italic', 'oblique'],
  'text-transform': [
    'none',
    'capitalize',
    'uppercase',
    'lowercase',
    'full-width',
  ],
  'text-decoration': ['none', 'underline', 'overline', 'line-through', 'blink'],
  'white-space': [
    'normal',
    'nowrap',
    'pre',
    'pre-wrap',
    'pre-line',
    'break-spaces',
  ],
  'word-break': [
    'normal',
    'break-all',
    'keep-all',
    'break-word',
    'break-spaces',
  ],
  cursor: [
    'auto',
    'default',
    'pointer',
    'text',
    'wait',
    'move',
    'not-allowed',
    'help',
    'crosshair',
    'grab',
    'grabbing',
  ],
  'border-style': [
    'none',
    'hidden',
    'dotted',
    'dashed',
    'solid',
    'double',
    'groove',
    'ridge',
    'inset',
    'outset',
  ],
  'box-sizing': ['content-box', 'border-box'],
  'flex-direction': ['row', 'row-reverse', 'column', 'column-reverse'],
  'flex-wrap': ['nowrap', 'wrap', 'wrap-reverse'],
  'justify-content': [
    'flex-start',
    'flex-end',
    'center',
    'space-between',
    'space-around',
    'space-evenly',
  ],
  'align-items': ['stretch', 'flex-start', 'flex-end', 'center', 'baseline'],
  'align-self': [
    'auto',
    'stretch',
    'flex-start',
    'flex-end',
    'center',
    'baseline',
  ],
  'grid-template-columns': [
    'none',
    'auto',
    '1fr',
    'repeat()',
    'minmax()',
    'fit-content()',
  ],
  'grid-template-rows': [
    'none',
    'auto',
    '1fr',
    'repeat()',
    'minmax()',
    'fit-content()',
  ],
  'transition-timing-function': [
    'ease',
    'linear',
    'ease-in',
    'ease-out',
    'ease-in-out',
    'cubic-bezier()',
    'steps()',
  ],
  'animation-timing-function': [
    'ease',
    'linear',
    'ease-in',
    'ease-out',
    'ease-in-out',
    'cubic-bezier()',
    'steps()',
  ],
};

// Common CSS units and values
export const COMMON_VALUES = [
  // Units
  'px',
  'em',
  'rem',
  'vh',
  'vw',
  '%',
  'auto',
  'inherit',
  'initial',
  'unset',
  // Colors
  'transparent',
  'currentColor',
  'black',
  'white',
  'red',
  'green',
  'blue',
  'yellow',
  'orange',
  'purple',
  'pink',
  'gray',
  // Numbers
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '10',
  '20',
  '50',
  '100',
  '200',
  '500',
  '1000',
  // Common values
  'none',
  'hidden',
  'visible',
  'normal',
  'bold',
  'italic',
  'underline',
  'center',
  'left',
  'right',
  'top',
  'bottom',
];
